name: Download data and run charts

on:
  push:
    branches: main
  #schedule:
    #- cron: '18 21 * * 5' GitHub Actions runs on UTC
  
  # run manually from Actions
  workflow_dispatch:

jobs:
  import-data:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ${{ github.workspace }}

    env:
      REPO_DIR: $HOME/work/explorations/explorations

    steps:
      - name: set up R env
        uses: r-lib/actions/setup-r@v2
        
      - name: install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::stringr
            any::tidyr
            any::ggplot2
            any::lubridate
            any::xml2
            any::httr
            any::purrr
            any::feather
            any::data.table
            any::dtplyr
            any::RColorBrewer
            any::scales
            any::rmarkdown
            any::here
            any::xfun

      - name: check out repository
        uses: actions/checkout@v3
        
      - uses: r-lib/actions/setup-pandoc@v2

      - name: download data
        run: curl -o $REPO_DIR/data/FRB_H8.zip "https://www.federalreserve.gov/datadownload/Output.aspx?rel=H8&filetype=zip"
        
      - name: check download
        run: file $REPO_DIR/data/FRB_H8.zip
        
      - name: unzip
        run: |
          cd $REPO_DIR/data/
          unzip -o FRB_H8.zip 'H8_data.xml'
      
      - name: convert data to intermediate files
        run: Rscript inst/convert_xml_to_dfs.R
        
      - name: check intermediate files
        run: ls -alt data/

      - name: run reports
        run: Rscript inst/run_reports.R
      
      - name: commit and push changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add reports/*.html
          git commit -m 'Recurring report update'
          git push origin main

