name: Download data and run charts

on:
  push:
    branches: main
  #schedule:
    #- cron: '18 21 * * 5' GitHub Actions runs on UTC
  
  # run manually from Actions
  workflow_dispatch:

jobs:
  import-data:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ${{ github.workspace }}
    steps:
      - name: set up R env
        uses: r-lib/actions/setup-r@v2
        
      - name: install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::stringr
            any::tidyr
            any::ggplot2
            any::lubridate
            any::xml2
            any::httr
            any::purrr
            any::feather
            any::data.table
            any::dtplyr
            any::RColorBrewer
            any::scales
            any::rmarkdown

      - name: check out repository
        uses: actions/checkout@v3
        
      - uses: r-lib/actions/setup-pandoc@v2

      - name: download data
        run:  |
          zip ./data/FRB_H8.zip anyfile
          zip -d ./data/FRB_H8.zip anyfile
          #Rscript inst/convert_xml_to_dfs.R /home/runner/work/explorations/explorations/
          Rscript inst/convert_xml_to_dfs.R .

      - name: run reports
        run:  |
          #Rscript inst/run_reports.R /home/runner/work/explorations/explorations/
          Rscript -e 'rmarkdown::render(input = "reports/simple_diffs.Rmd",
                                        params = list(
                                          program_path = /home/runner/work/explorations/explorations/R/,
                                          date_max = Sys.Date() - 7
                                        ))'
          Rscript -e 'rmarkdown::render(input = "reports/sa_comps.Rmd",
                                        params = list(
                                          program_path = /home/runner/work/explorations/explorations/R/,
                                          date_max = Sys.Date() - 7
                                        ))'
