name: Download data and update charts

on:
  push:
    branches: main
  #schedule:
    #- cron: '18 21 * * 5' GitHub Actions runs on UTC
    #- cron: '*/20 * * * *' #test

permissions:
  contents: write

jobs:
  import-data:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ${{ github.workspace }}
    steps:
      - name: set up R env
        uses: r-lib/actions/setup-r@v2
        
      - name: install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr
            any::stringr
            any::tidyr
            any::ggplot2
            any::lubridate
            any::xml2
            any::httr
            any::purrr
            any::feather
            any::data.table
            any::dtplyr
            any::RColorBrewer
            any::scales
            any::rmarkdown

      - name: check out repository
        uses: actions/checkout@v3

      - name: download data
        run:  |
          #cd /home/runner/work/explorations/explorations/
          #Rscript inst/convert_xml_to_dfs.R /home/runner/work/explorations/explorations/
          Rscript inst/convert_xml_to_dfs.R .

      - name: run reports
        run:  |
          #cd /home/runner/work/explorations/explorations/
          #Rscript inst/run_reports.R /home/runner/work/explorations/explorations/
          Rscript inst/run_reports.R .

      - name: commit reports
        run:  |
          echo "running"
          #cd /home/runner/work/explorations/explorations/
          git config --local user.name github-actions
          git config --local user.email "actions@github.com"
          git add reports/sa_comps.html
          git add reports/simple_diffs.html
          git commit -m 'data updated'
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions

